name: Deploy Application

on:
 push:
    branches:
       - master

jobs:
 create-deployment-artifacts:
   name: Create deployment artifacts
   runs-on: ubuntu-latest
   steps:
     -uses: actions/checkout@v2

     -name: Compile CSS 
       run: npm install
     -name: Compile  Javascript
       run: npm run prod